#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""interface to read and assemble footprints generated by TM5 adoint tracer run."""

#-- system packages
import sys
import os
from omegaconf import OmegaConf, DictConfig
from pathlib import Path
from collections import OrderedDict
from loguru import logger
from pandas import date_range, DataFrame, Series
from pandas import Timestamp, Timedelta, concat
import xarray as xr
import numpy as np
from numpy import zeros, tile
from numpy.typing import NDArray
from netCDF4 import Dataset, chartostring
from types import SimpleNamespace
#-- library packages
from tm5.gridtools import TM5Grids
from tm5.fitic import read_obs_table


#
#-- table of FIT-IC regions
#   TODO: should not be hard-coded here!
#
region_table = OrderedDict()
region_table['glb600x400'] = SimpleNamespace(
    grid=TM5Grids.from_corners(west=-180, east=180, south=-90, north=90, dlon=6, dlat=4),
    child='eur300x200', parent=None)
region_table['eur300x200'] = SimpleNamespace(
    grid=TM5Grids.from_corners(west=-36, east=54, south=22, north=74, dlon=3, dlat=2),
    child='gns100x100', parent='glb600x400')
region_table['gns100x100'] = SimpleNamespace(
    grid=TM5Grids.from_corners(west=0, east=18, south=42, north=58, dlon=1, dlat=1),
    child=None, parent='eur300x200')


def regiondomain_halo( region : str ) -> list:
    reginfo = region_table[region]
    lonmin,lonmax,latmin,latmax = reginfo.grid.domain
    #
    #-- drop the halo zone
    #
    if reginfo.parent!=None:
        dlon = region_table[reginfo.parent].grid.dlon
        dlat = region_table[reginfo.parent].grid.dlat
        lonmin = lonmin+dlon
        lonmax = lonmax-dlon
        latmin = latmin+dlat
        latmax = latmax-dlat
    return [lonmin,lonmax,latmin,latmax,]


def tm5rundir_obstable( outpath : str | Path, host : str = 'cosmos') -> DataFrame:
    yamlfile = Path(outpath) / 'tm5.yaml'
    if not yamlfile.exists():
        msg = f"yaml configuration file ***{str(yamlfile)}*** not found on system."
        raise FileNotFoundError(msg)
    conf = OmegaConf.load(yamlfile)
    conf.host = conf[host]

    # Load the observations tabled
    obs_table = read_obs_table(conf.observations.file).set_index('obsid')
    return obs_table


def tm5rundir_obsids_extra(outpath : str | Path) -> OrderedDict:
    """
    """
    #-- extract information from point departure file
    pdepfile = Path(outpath) / 'point' / 'point_departures.nc4'
    if not pdepfile.exists():
        msg = f"point departure file ***{str(pdepfile)}*** not found on system."
        raise FileNotFoundError(msg)
    fp = Dataset(str(pdepfile))
    #-- for now restrict to FIT-IC domain setup
    obs_table = OrderedDict()
    for reg in region_table.keys():
        if reg in fp.groups:
            reg_grp = fp.groups[reg]
            #-- each tracer/obsid defines a separate group
            for obsid in reg_grp.groups:
                obs_grp = reg_grp.groups[obsid]
                #-- should be single sample here
                assert obs_grp.dimensions['samples'].size==1
                assert obs_grp['/obsid'][0]==obsid #-- just consistency
                lon = obs_grp['/lon'][:].data[0]
                lat = obs_grp['/lat'][:].data[0]
                alt = obs_grp['/alt'][:].data[0]
                date_components = obs_grp['/date_components'][0]
                assert np.all(date_components[4:]==0)
                yr,mn,dy,hr = date_components[:4]
                time_window_length = obs_grp['/time_window_length'][:].data[0] # [s]
                tmid = Timestamp(f"{yr:04d}-{mn:02d}-{dy:02d}T{hr:02d}")
                tstart = tmid - Timedelta(seconds=time_window_length)
                tend   = tmid + Timedelta(seconds=time_window_length)
                obs_table[obsid] = SimpleNamespace(
                    lon=lon, lat=lat, alt=alt, tstart=tstart, tend=tend)
                    
    fp.close()

    return obs_table


def tm5rundir_iniconc_1obs( outpath : str | Path, obs_info : Series, host : str = 'cosmos' ) -> SimpleNamespace:
    """
    """
    yamlfile = Path(outpath) / 'tm5.yaml'
    if not yamlfile.exists():
        msg = f"yaml configuration file ***{str(yamlfile)}*** not found on system."
        raise FileNotFoundError(msg)
    dconf = OmegaConf.load(yamlfile)
    dconf.host = dconf[host]
    reglist = dconf.run.regions
    #
    #--
    #
    sta_tracer = obs_info.tracer
    sta_id     = obs_info.station_id
    sta_lon    = obs_info.lon
    sta_lat    = obs_info.lat
    #-- determine innermost zoom region of station
    sta_region = None
    for reg in reglist[::-1]:
        lonw,lone = dconf.regions[reg].lons[:2]
        lats,latn = dconf.regions[reg].lats[:2]
        if lonw<=sta_lon<=lone and lats<=sta_lat<=latn:
            sta_region = reg
            break
    # msg = f"sta_id={sta_id} detected in region -->{sta_region}<--"
    # print(msg)
    #
    #-- read from point output file
    #   - group structure in file is <region>/<tracer>
    #
    outp_file = Path(outpath) / 'point' / 'point_output.nc4'
    if not outp_file.exists():
        msg = f"expected point output file ***{str(outp_file)}*** not found."
        raise FileNotFoundError(msg)
    #
    #-- select region/tracer for current observation
    #
    outp = xr.open_dataset(outp_file, group=f'{sta_region}/{sta_tracer}').to_dataframe()
    #
    #-- extract only selected station
    #
    sta_outp = outp.set_index('station_id').loc[sta_id,:]
    # msg = f"@{outpath.name}, sta_id={sta_id} conc={sta_outp.mixing_ratio}"
    # print(msg)
    return SimpleNamespace(conc=sta_outp.mixing_ratio, nsamples=sta_outp.nsamples, averaging_time=sta_outp.averaging_time)


def tm5rundir_iniconc_wrong( outpath : str | Path, obsid : str, host : str = 'cosmos', trange : date_range = None ) -> SimpleNamespace:
    """
    """
    yamlfile = Path(outpath) / 'tm5.yaml'
    if not yamlfile.exists():
        msg = f"yaml configuration file ***{str(yamlfile)}*** not found on system."
        raise FileNotFoundError(msg)
    dconf = OmegaConf.load(yamlfile)
    dconf.host = dconf[host]
    if trange is None:
        tstart = Timestamp(dconf.run.start)
        tend   = Timestamp(dconf.run.end)
        trange = date_range(tstart, tend, freq='1d')
    else:
        tstart = trange[0]
        tend   = trange[-1]
    station_file = Path(outpath) / 'stations' / 'stations.nc4'
    ds = Dataset(station_file)
    assert ds.dimensions['tracers'].size==1, \
        f"multiple tracers in station file not yet supported " \
        f"({str(station_file)})"
    grp_fnd = None
    for g,gg in ds.groups.items():
        if gg.abbr.endswith(obsid):
            grp_fnd = gg
    #
    if grp_fnd is None:
        raise RuntimeError(f"-->{obsid}<-- not found in station file ***{str(station_file)}***")
    else:
        print(grp_fnd)
    #
    #-- closes time-point to detected tstart
    #
    times = np.array([Timestamp(*_) for _ in ds['date_midpoints'][:]]).astype('datetime64[s]')
    istart = np.argmin(np.abs(times-tstart.to_datetime64()))
    tini = times[istart]
    msg = f"closest time-point to {tstart} detected at istart={istart} -->{tini}"
    print(msg)
    ncvar = grp_fnd['/mixing_ratio']
    if not ncvar.dimensions!=('tracer','samples'):
        msg = f"mixing_ratio with unexpected dimensions -->{ncvar.dimensions}<--"
        raise RuntimeError(msg)
    iniconc = ncvar[0,istart]
    msg = f"...{obsid}@{tini}, conc={iniconc}"
    print(msg)
    ds.close()
    return SimpleNamespace(iniconc=iniconc, initime=tini)

    
def tm5rundir_emissions1D( outpath : str | Path, trange : date_range = None ) -> SimpleNamespace:
    """
    """
    yamlfile = Path(outpath) / 'tm5.yaml'
    if not yamlfile.exists():
        msg = f"yaml configuration file ***{str(yamlfile)}*** not found on system."
        raise FileNotFoundError(msg)
    dconf = OmegaConf.load(yamlfile)
    emisdir = dconf.run.paths.emissions
    regions = dconf.run.regions
    if trange is None:
        tstart = Timestamp(dconf.run.start)
        tend   = Timestamp(dconf.run.end)
        trange = date_range(tstart, tend, freq='1d')
    # msg = f"emission directory ***{emisdir}***, regions -->{regions}<-- " \
    #     f"trange first/last = {trange[0]}/{trange[-1]}"
    # print(msg)
    #
    #-- reformat collected emissions values to 1D array
    #   ordering:
    #   - emisday1
    #     - grid-cells glb600x400 (flattened)
    #     - grid-cells eur300x200 (flattened)
    #     - grid-cells gns100x100 (flattened)
    #   - emisday2
    #     - grid-cells glb600x400 (flattened)
    #   .
    #   .
    #   .
    emissions_list = []
    iday_list = []
    region_list = []
    for iday,day in enumerate(trange):
        for reg in regions:
            #-- TODO:: 'CH4' is hard-coded here!
            fpath = Path(day.strftime(f'{dconf.emissions.CH4.prefix}.CH4.{reg}.%Y%m%d.nc'))
            if not fpath.exists():
                msg = f"expected emissions file ***{str(fpath)}*** not found on system."
                raise FileNotFoundError(msg)
            em = xr.open_dataset(fpath)
            #-- sum-up total emissions
            emtot = em.to_array().sum('variable').values
            #-- turn 2D spatial part into 1D
            emtot = emtot.ravel()
            nemis = len(emtot)
            emissions_list.append(emtot)
            iday_list.append(np.full((nemis,), iday, dtype='i4'))
            region_list.append(np.array([reg,]*nemis))
    #-- stack into single 1D array
    emissions1D = np.hstack(emissions_list)
    iday1D = np.hstack(iday_list)
    region1D = np.hstack(region_list)
    return SimpleNamespace(emis1D=emissions1D, iday1D=iday1D, region1D=region1D)


def tm5rundir_jacobian2D( outpath : str | Path, trange : date_range = None, obsid : str|None = None ) -> NDArray:
    """
    will yield an array of shape jac(nobs,nemis)
    nemis comprises emissionday and emission location into a single 1D array of order
    - day1
      - reg1 (flattened)
      - reg2 (flattened)
      - reg3 (flattened)
    - day2
      - reg1 (flattened)
      .
      .
      .
    """
    #
    #-- load footprints into dataframe, plus ancillary information
    #
    fpinfo = tm5_fitic_adjoint_corrected_halos(outpath, trange)
    footp_df = fpinfo.data
    obsids   = fpinfo.obsids
    days     = fpinfo.days
    regions  = fpinfo.regions
    nobs = len(obsids)
    nday = len(days)
    msg = f"...footprint data read, nfootp={len(footp_df)} for nobs/nday = {nobs}/{nday}"
    logger.debug(msg)
    if obsid!=None:
        msg = f"...extract only for observation -->{obsid}<--"
        logger.info(msg)
        itrac = obsids.index(obsid) #-- position of obs. in list of tracers/obs
        cnd_obs = footp_df.loc[:,'itrac']==itrac
        footp_df = footp_df.loc[cnd_obs,:]
        msg = f"......{len(footp_df)} remaining footprints."
        logger.info(msg)
        itrac_list = [ obsids.index(obsid), ]
        # for iday in range(nday):
        #     for reg in region_table.keys():
        #         cnd = (footp_df.loc[:,'itime']==iday)&(footp_df.loc[:,'region']==reg)
        #         dd = footp_df.loc[cnd,:]
        #         sens = dd.loc[:,'value'].values
        #         msg = f"@{obsid}, {days[iday].strftime('%Y%m%d')}, {reg}: " \
        #             f"sens_values min/mean/max = {sens.min()}/{sens.mean()}/{sens.max()}"
        #         print(msg)
    else:
        itrac_list = np.arange(nobs)
    #
    #--
    #
    jacobian2D = None
    for itrac in itrac_list:
        cur_obsid = obsids[itrac]
        cnd_obs = footp_df.loc[:,'itrac']==itrac
        df = footp_df.loc[cnd_obs,:]
        msg = f"...restricted to {cur_obsid} yields {len(df)} entries"
        logger.debug(msg)
        jac_list = []
        for iday in range(nday):
            cnd_day = df.loc[:,'itime']==iday
            df_day = df.loc[cnd_day,:]
            msg = f"...restricted to {days[iday].strftime('%Y%m%d')} yields {len(df_day)} entries"
            logger.debug(msg)
            for reg in regions:
                # print(f"@{reg}\n", df.head())
                cnd_reg = df_day.loc[:,'region']==reg
                df_reg = df_day.loc[cnd_reg,:]
                msg = f"...restricted to {reg} yields {len(df_reg)} entries"
                logger.debug(msg)
                grid = region_table[reg].grid
                # print(f"@{reg}, nlat/nlon = {grid.nlat}/{grid.nlon}")
                sens = zeros((grid.nlat, grid.nlon))
                sens[df_reg.ilat, df_reg.ilon] = df_reg.value
                #
                sens = sens.ravel()
                jac_list.append(sens)
        jac_obs = np.hstack(jac_list)
        if jacobian2D is None:
            jacobian2D = jac_obs.reshape(1,len(jac_obs))
        else:
            jacobian2D = np.vstack(jacobian2D, jac_obs)
    #
    return SimpleNamespace(jac2D=jacobian2D, days=days, obsids=obsids, regions=regions)


def tm5_fitic_footprint4jacobian_v1( outpath : str|Path, trange : date_range = None, obsid : str|None = None ) -> SimpleNamespace:
    """Routine to collect footprint data from TM5 adjoint run for a series of observations
    for one or multiple sites at dedicated periods on the same day.
    """
    #
    #-- load footprints into dataframe, plus ancillary information
    #
    fpinfo = tm5_fitic_adjoint_corrected_halos(outpath, trange)
    footp_df = fpinfo.data
    obsids   = fpinfo.obsids
    days     = fpinfo.days
    regions  = fpinfo.regions
    nobs = len(obsids)
    nday = len(days)
    msg = f"...footprint data read, nfootp={len(footp_df)} for nobs/nday = {nobs}/{nday}"
    logger.debug(msg)
    if obsid!=None:
        msg = f"...extract only for observation -->{obsid}<--"
        logger.info(msg)
        itrac = obsids.index(obsid) #-- position of obs. in list of tracers/obs
        cnd_obs = footp_df.loc[:,'itrac']==itrac
        footp_df = footp_df.loc[cnd_obs,:]
        msg = f"......{len(footp_df)} remaining footprints."
        logger.info(msg)
        nobs = 1
        # for iday in range(nday):
        #     for reg in region_table.keys():
        #         cnd = (footp_df.loc[:,'itime']==iday)&(footp_df.loc[:,'region']==reg)
        #         dd = footp_df.loc[cnd,:]
        #         sens = dd.loc[:,'value'].values
        #         msg = f"@{obsid}, {days[iday].strftime('%Y%m%d')}, {reg}: " \
        #             f"sens_values min/mean/max = {sens.min()}/{sens.mean()}/{sens.max()}"
        #         print(msg)
    #
    #--
    #
    jac_table = OrderedDict()
    for region in region_table.keys():
        cnd_reg = footp_df.loc[:,'region']==region
        footp_reg = footp_df.loc[cnd_reg, :]
        grid = region_table[region].grid
        west,east,south,north = grid.domain
        dlon,dlat = grid.dlon, grid.dlat
        if nobs>1:
            fpfield = zeros((nday, grid.nlat, grid.nlon, nobs))
            fpfield[footp_reg.itime, footp_reg.ilat, footp_reg.ilon, footp_reg.itrac] = footp_reg.value
            fpda = xr.DataArray(
                fpfield,
                dims=('iday','lat','lon','iobs'),
                coords = {
                    'iday': np.arange(nday),
                    'lat': grid.latc,
                    'lon': grid.lonc,
                    'iobs': np.arange(nobs)
                    },
                attrs = {
                    'units' : "ppb/kgCH4/cell/s"
                    }
                )
        else:
            fpfield = zeros((nday, grid.nlat, grid.nlon))
            fpfield[footp_reg.itime, footp_reg.ilat, footp_reg.ilon] = footp_reg.value
            fpda = xr.DataArray(
                fpfield,
                name='jac',
                dims=('iday','lat','lon'),
                coords = {
                    'iday': np.arange(nday),
                    'lat': grid.latc,
                    'lon': grid.lonc
                    },
                attrs = {
                    'units' : "ppb/kgCH4/cell/s"
                    }
                )
        jac_table[region] = fpda
    return SimpleNamespace(jac_table=jac_table, days=days, obsids=obsids)


def tm5_fitic_adjoint_corrected_halos( outpath : str|Path, trange : date_range = None) -> SimpleNamespace:
    """Function to read and collect footprint information from one TM5 adjoint run
    for selected period of time into a pandas dataframe for further processing.
    outpath must be the toplevel output directory of the TM5 forward and adjoint run,
    that also contains the rc-configuration files.
    The dataframe will contain 

    Currently it is expected that the simulation was carried on the FIT-IC spatial zoom
    domain.

    This routine handles the HALOs of the two inner zoom domains (eur300x200, gns100x100).
    """
    yamlfile = Path(outpath) / 'tm5.yaml'
    if not yamlfile.exists():
        msg = f"yaml configuration file ***{str(yamlfile)}*** not found on system."
        raise FileNotFoundError(msg)
    dconf = OmegaConf.load(yamlfile)
    #
    #-- get name of tracer/obsids
    #
    obs_table = tm5rundir_obstable(outpath)
    tracer = list(obs_table.index)
    
    #
    #-- collect adjoint emission files
    #
    adjemis_dir = Path(outpath) / 'adjemis'   
    emisfile_list = sorted(list(adjemis_dir.glob(f"adjemis.*.nc")))
    #
    #-- determine regions
    #
    region_list = dconf.run.regions
    assert region_list==list(region_table.keys())
    #
    #-- set temporal domain
    #
    if trange is None:
        trange = date_range(dconf.run.start, dconf.run.end, freq='1d')
    #
    #-- dictionary for collecting footprint results
    #
    footprints = { 'ilat':[],
                   'ilon':[],
                   'latc':[],  #-- only for diagnostics
                   'lonc':[],  #-- only for diagnostics
                   'itime':[],
                   'value':[],
                   'region':[],
                   'itrac':[]   }
    #
    #-- MVO-20260424:
    #   - dataasets in adjoint emissions files are written as long 1D arrays (dimension: point),
    #     variable 'int itrac(point)' provides index of associated tracer
    #   - Thus, there should be *no* need to loop along the tracer !?
    for iday, day in enumerate(trange):
        for ireg, region in enumerate(region_list):
            fname = adjemis_dir / day.strftime(f'adjemis.{region}.%Y%m%d.nc')
            # Adjoint files are written only if needed, so it may not exist for a given day/region
            if not fname.exists():
                continue
            with Dataset(fname, 'r') as ds:
                ilat = ds['ilat'][:].data
                ilon = ds['ilon'][:].data
                itrac = ds['itrac'][:].data
                values = ds['values'][:].data
                lonc = ds['lon'][:].data
                latc = ds['lat'][:].data
                lonc = lonc[ilon]
                latc = latc[ilat]
                nfootp = len(ilat)
            # print(f"@{region},{day.strftime('%Y-%m-%d')}: " \
            #       f"ilon min/max={min(ilon)}/{max(ilon)}, " \
            #       f"ilat min/max={min(ilat)}/{max(ilat)}, ")
            #
            #-- halo correction
            #
            # if iday==0:
            #     nfootp = len(ilat)
            #     print(f"@{region},{day.strftime('%Y-%m-%d')}: #footprints={nfootp}")
            if region=='gns100x100':
                #
                #- on zonal and 
                #
                lonmin,lonmax,latmin,latmax = regiondomain_halo(region)
                cnd_lon = (lonc>=lonmin)&(lonc<=lonmax)
                cnd_lat = (latc>=latmin)&(latc<=latmax)
                cnd_halo = cnd_lon&cnd_lat
                print(f"@{region},{day.strftime('%Y-%m-%d')}, nfootp prior/post filtering = " \
                      f"{nfootp}/{np.count_nonzero(cnd_halo)}")
            elif region=='eur300x200':
                #-- initial approach:
                #   (1) restrict to halo corrected domain of region
                #   (2) remove parts from the inner-most zoom domain
                #
                # lonmin1,lonmax2,latmin1,latmax2 = regiondomain_halo(region)
                # lonmax1,lonmin2,latmax1,latmin2 = regiondomain_halo(region_table[region].child)
                # cnd_lon = ((lonc>=lonmin1)&(lonc<=lonmax1))|((lonc>=lonmin2)&(lonc<=lonmax2))
                # cnd_lat = ((latc>=latmin1)&(latc<=latmax1))|((latc>=latmin2)&(latc<=latmax2))
                # cnd_halo = cnd_lon&cnd_lat
                # MVO: 2026-04-29, Guillaume confirmed that removal of "inner" part
                #                  is handled within TM5
                lonmin,lonmax,latmin,latmax = regiondomain_halo(region)
                cnd_lon = (lonc>=lonmin)&(lonc<=lonmax)
                cnd_lat = (latc>=latmin)&(latc<=latmax)
                cnd_halo = cnd_lon&cnd_lat
                # print(f"@{region},{day.strftime('%Y-%m-%d')}, nfootp prior/post filtering = " \
                #       f"{nfootp}/{np.count_nonzero(cnd_halo)}")
            elif region=='glb600x400':
                #-- initial approach:
                #   (1) restrict to halo corrected domain of region
                #   (2) remove parts from the inner-most zoom domain
                #
                # lonmin1,lonmax2,latmin1,latmax2 = regiondomain_halo(region)
                # lonmax1,lonmin2,latmax1,latmin2 = regiondomain_halo(region_table[region].child)
                # cnd_lon = ((lonc>=lonmin1)&(lonc<=lonmax1))|((lonc>=lonmin2)&(lonc<=lonmax2))
                # cnd_lat = ((latc>=latmin1)&(latc<=latmax1))|((latc>=latmin2)&(latc<=latmax2))
                # cnd_halo = cnd_lon&cnd_lat
                # print(f"@{region},{day.strftime('%Y-%m-%d')}, nfootp prior/post filtering = " \
                #       f"{nfootp}/{np.count_nonzero(cnd_halo)}")
                # MVO: 2026-04-29, Guillaume confirmed that removal of "inner" part
                #                  is handled within TM5
                # => for the global domain there are no halos to correct!
                # => all collected footprints are taken
                cnd_halo = np.full(len(ilat), True)
            ##
            idxs_halo = np.where(cnd_halo)
            ilat = ilat[idxs_halo]
            ilon = ilon[idxs_halo]
            itrac = itrac[idxs_halo]
            values = values[idxs_halo]
            lonc = lonc[idxs_halo]
            latc = latc[idxs_halo]
            nfootp = len(ilat)
            #
            #-- cbw_207 at second position
            #
            icbw = np.where(itrac==1)
            vcbw = values[icbw]
            # msg = f"DEBUG@cbw_207, {day.strftime('%Y-%m-%d')}, {region}: " \
            #     f"values min/mean/max = {vcbw.min()}/{vcbw.mean()}/{vcbw.max()}"
            # print(msg)
            # if iday==0:
            #     msg = f"@{region},{day.strftime('%Y-%m-%d')}: after halo-correction " \
            #         f"remaining footprints={len(idxs_halo[0])}"
            #     print(msg)

            footprints['ilat'].extend(ilat)
            footprints['ilon'].extend(ilon)
            footprints['latc'].extend(latc)
            footprints['lonc'].extend(lonc)
            footprints['itime'].extend([iday] * nfootp)
            footprints['value'].extend(values)
            footprints['itrac'].extend(itrac)
            footprints['region'].extend([region] * nfootp)
    footprints = DataFrame.from_dict(footprints)
    msg = f"...overall #footprints={len(footprints)}"
    logger.info(msg)
    return SimpleNamespace(data=footprints, days=trange, regions=region_list, obsids=tracer)


def load_adjoint_fitic_footprint(conf : DictConfig) -> SimpleNamespace:
    """Function to extract footprints from single TM5 adjoint run
    together with information of the temporal coverage of the emissions
    and the observation identifiers.

    Code is based on parts from the Jupyter notebook 'forward_footprints.ipynb' that
    Guillaume had prepared for initial inspection and visualisation of the footprints.
    """
    outpath = Path(conf.run.paths.output)/'adjemis'
    regions = conf.run.regions
    start = Timestamp(conf.run.start)
    end = Timestamp(conf.run.end)

    
    #
    #-- be carefull regarding potential limitations we still have...
    #
    if regions!=['glb600x400', 'eur300x200', 'gns100x100']:
        msg = f"currently only the FIT-IC spatial setup is supported, but found " \
            f"-->{regions}<-- as regions in the configuration file."
        raise NotImplementedError(msg)
    
    #
    #-- determine tracers
    #   -> adjoint emissions directory should contain files adjemis.<region>.%Y%m%d.nc
    #      (expected at daily temporal resolution),
    #      all for the equal list of tracers.
    #   -> we deliberatly extract them from the first file
    #   -> MVO-NOTE, 20260424:
    #      - what is named here "tracer" is actually the (unique) observation identifier
    #        (taken from the point departure file) ingested into the adoint TM5 run.
    emisfile_list = sorted(list(outpath.glob(f"adjemis.*.nc")))
    emisfile = emisfile_list[0]
    with Dataset(emisfile, 'r') as ds:
        msg = f"...reading tracer information from file ***{emisfile}***"
        logger.debug(msg)
        nobs = ds.dimensions['tracer'].size
        tracer = chartostring(ds['/tracer'][:])
        tracer = [ _.strip() for _ in tracer ]
    #
    #--
    #
    trange = list(date_range(conf.run.start, conf.run.end, freq='1d'))[:-1]
    nday = len(trange)

    footprints = { 'ilat':[],
                   'ilon':[],
                   'itime':[],
                   'value':[],
                   'region':[],
                   'itrac':[]   }
    coords_table = {}
    #-- MVO-20260424:
    #   - dataasets in adjoint emissions files are written as long 1D arrays (dimension: point),
    #     variable 'int itrac(point)' provides index of associated tracer
    #   - Thus, there should be *no* need to loop along the tracer !?
    #-- temporal range (simulation ends at last day 0:00, this day is (typically) not simulated!)
    for iday, day in enumerate(trange):
        for ireg, region in enumerate(regions):
            fname = outpath / day.strftime(f'adjemis.{region}.%Y%m%d.nc')
            # Adjoint files are written only if needed, so it may not exist for a given day/region
            if not fname.exists():
                continue
            with Dataset(fname, 'r') as ds:
                ilat = ds['ilat'][:].data
                ilon = ds['ilon'][:].data
                itrac = ds['itrac'][:].data
                values = ds['values'][:].data
                lonc = ds['lon'][:].data
                latc = ds['lat'][:].data
            ndat = len(ilat)

            footprints['ilat'].extend(ilat)
            footprints['ilon'].extend(ilon)
            footprints['itime'].extend([iday] * ndat)
            footprints['value'].extend(values)
            footprints['itrac'].extend(itrac)
            footprints['region'].extend([region] * ndat)
            #-- store spatial coordinates for region (only once)
            if not region in coords_table:
                coords_table[region] = (lonc,latc)
    # for itrac in range(ntracer):
    #     for iday, day in enumerate(date_range(start, end, freq='d')):
    #         for ireg, region in enumerate(regions):
    #             fname = outpath / day.strftime(f'adjemis.{region}.%Y%m%d.nc')
    #             # Adjoint files are written only if needed, so it may not exist for a given day/region
    #             if not fname.exists():
    #                 continue
    #             with Dataset(fname, 'r') as ds:
    #                 ilat = ds['ilat'][:].data
    #                 ilon = ds['ilon'][:].data
    #                 itrac = ds['itrac'][:].data
    #                 values = ds['values'][:].data
    #                 lonc = ds['lon'][:].data
    #                 latc = ds['lat'][:].data
    #             ndat = len(ilat)

    #             footprints['ilat'].extend(ilat)
    #             footprints['ilon'].extend(ilon)
    #             footprints['itime'].extend([iday] * ndat)
    #             footprints['value'].extend(values)
    #             footprints['itrac'].extend(itrac)
    #             footprints['region'].extend([region] * ndat)
    #             #-- store spatial coordinates for region (only once)
    #             if not region in coords_table:
    #                 coords_table[region] = (lonc,latc)
    footprints = DataFrame.from_dict(footprints)

    # Correct the halos:
    r2 = footprints[footprints.region == 'eur300x200']
    # print("r2.ilon=",r2.ilon.values)
    # print("r2.ilat=",r2.ilat.values)
    footprints.loc[footprints.region == 'eur300x200', 'ilon'] = r2.ilon.values - 2
    footprints.loc[footprints.region == 'eur300x200', 'ilat'] = r2.ilat.values - 2
    r3 = footprints[footprints.region == 'gns100x100']
    # print("r3.ilon=",r3.ilon.values)
    # print("r3.ilat=",r3.ilat.values)
    footprints.loc[footprints.region == 'gns100x100', 'ilon'] = r3.ilon.values - 3
    footprints.loc[footprints.region == 'gns100x100', 'ilat'] = r3.ilat.values - 2

    
    # ------------------
    # Reproject the eur3x2 data on a 1x1 grid
    eur_west, eur_east = conf.regions['eur300x200'].lons[:2]
    eur_south, eur_north = conf.regions['eur300x200'].lats[:2]
    fpreg = footprints[footprints.region == 'eur300x200']
    grid0 = TM5Grids.from_corners(west=eur_west+6, east=eur_east-6, south=eur_south+4, north=eur_north-4, dlon=3, dlat=2)
    grid1 = TM5Grids.from_corners(west=eur_west+6, east=eur_east-6, south=eur_south+4, north=eur_north-4, dlon=1, dlat=1)

    # Duplicate the points
    rlon, rlat = 3, 2
    # print(f"#ilat={len(fpreg.ilat.values)}, #ilon={len(fpreg.ilon.values)}")
    # x = tile(fpreg.value.values, (rlat, rlon, 1))
    # print(f"x.shape={x.shape}")
    # x = x.reshape(-1)
    # print(f"x.shape={x.shape}")
    ilat = tile(fpreg.ilat.values * rlat, (rlat, rlon, 1))
    ilon = tile(fpreg.ilon.values * rlon, (rlat, rlon, 1))
    values = tile(fpreg.value.values, (rlat, rlon, 1)).reshape(-1)
    itime = tile(fpreg.itime.values, (rlat, rlon, 1)).reshape(-1)
    itrac = tile(fpreg.itrac.values, (rlat, rlon, 1)).reshape(-1)

    # Adjust the indices
    for jj in range(rlat):
        ilat[jj, :, :] += jj
    for ii in range(rlon):
        ilon[:, ii, :] += ii

    # Re-create a DataFrame:
    df_eur = DataFrame.from_dict(dict(ilat=ilat.reshape(-1), ilon=ilon.reshape(-1), value=values, itime=itime, itrac=itrac))
    df_eur.loc[:, 'region'] = 'eur300x200'

    # Adjust the indices to those of a glb1x1 grid:
    df_eur.loc[:, 'ilat'] += grid1.south + 90
    df_eur.loc[:, 'ilon'] += grid1.west + 180

    # ------------------
    # Reproject the glb6x4 grid on glo1x1
    fpreg = footprints[footprints.region == 'glb600x400']
    grid0 = TM5Grids.from_corners(west=-180, east=180, south=-90, north=90, dlon=6, dlat=4)
    grid1 = TM5Grids.from_corners(west=-180, east=180, south=-90, north=90, dlon=1, dlat=1)
    grid1x1 = grid1

    rlon, rlat = 6, 4
    ilat = tile(fpreg.ilat.values * rlat, (rlat, rlon, 1))
    ilon = tile(fpreg.ilon.values * rlon, (rlat, rlon, 1))
    values = tile(fpreg.value.values, (rlat, rlon, 1)).reshape(-1)
    itime = tile(fpreg.itime.values, (rlat, rlon, 1)).reshape(-1)
    itrac = tile(fpreg.itrac.values, (rlat, rlon, 1)).reshape(-1)

    for jj in range(rlat):
        ilat[jj, :, :] += jj
    for ii in range(rlon):
        ilon[:, ii, :] += ii

    df_glb = DataFrame.from_dict(dict(ilat=ilat.reshape(-1), ilon=ilon.reshape(-1), value=values, itime=itime, itrac=itrac))
    df_glb.loc[:, 'region'] = 'eur600x400'

    # ---------------------
    # Finally reproject gns1x1 on glo1x1
    df_gns = footprints[footprints.region == 'gns100x100']
    gns_west, gns_east = conf.regions['gns100x100'].lons[:2]
    gns_south, gns_north = conf.regions['gns100x100'].lats[:2]
    
    grid0 = TM5Grids.from_corners(west=gns_west+3, east=gns_east-3, south=gns_south+2, north=gns_north-2, dlon=1, dlat=1)
    df_gns.loc[:, 'ilat'] += grid0.south + 90
    df_gns.loc[:, 'ilon'] += grid0.west + 180

    # ----------------------
    # Concatenate all 3 dataframes

    df_tot = concat([df_eur, df_glb, df_gns])

    # Store all footprints in a single array
    # - array is global with dimensions time/lat/lon/obs
    #
    fp = zeros((nday, 180, 360, nobs))
    fp[df_tot.itime, df_tot.ilat, df_tot.ilon, df_tot.itrac] = df_tot.value
    #-- MVO-TODO::still hard-coding the units below!!
    da = xr.DataArray(
        fp,
        dims=('iday','lat','lon','iobs'),
        coords = {
            'iday': np.arange(nday),
            'lat': grid1x1.latc,
            'lon': grid1x1.lonc,
            'iobs': np.arange(nobs)
            },
        attrs = {
            'units' : "ppb/kgCH4/cell/s"
            }
        )
    
    return SimpleNamespace(data_table=df_tot, data=da, obsids=tracer, days=trange)


def load_adjoint_fwd(outpath : str | Path, host : str = 'cosmos', trange : date_range = None) -> DataFrame:
    """Function that codes the first cell of Guillaume's initial jupyter notebook.

    Returns pandas dataframe, where each row contains the contribution of one (emission)
    date and region to one specific obs.
    """
    yamlfile = Path(outpath) / 'tm5.yaml'
    if not yamlfile.exists():
        msg = f"yaml configuration file ***{str(yamlfile)}*** not found on system."
        raise FileNotFoundError(msg)
    conf = OmegaConf.load(yamlfile)
    conf.host = conf[host]

    # Load the observations tabled
    obs_table = read_obs_table(conf.observations.file).set_index('obsid')
    tracers = set(obs_table.tracer)
    # print(f"-->{obs_table.index}<--")
    # sta = 'cbw_207'
    # ii = np.where(obs_table.index==sta)
    # ista = ii[0][0]
    # print(f"{sta} detected at position {ista}")
    # Accumulators:
    date, region, obs, dmix = [], [], [], []

    if trange is None:
        trange = date_range(conf.run.start, conf.run.end, freq='1d')

    dmix_sta = []
    for day in trange:
        for reg in conf.run.regions:
            adjfile = day.strftime(f'{conf.run.paths.output}/adjemis/adjemis.{reg}.%Y%m%d.nc')

            # Adjoint files are written only if needed, so it may not exist for a given day/region
            if not Path(adjfile).exists():
                continue

            # I don't know which key should code for that exact path ... for now I guessed ...
            adj = xr.open_dataset(day.strftime(f'{conf.run.paths.output}/adjemis/adjemis.{reg}.%Y%m%d.nc'))

            ilons = adj.ilon.values
            ilats = adj.ilat.values
            sensi = adj['values'].values
            itrac = adj.itrac.values

            # Read the emissions. For now, I'm hardcoding this to CH4 ...
            em = xr.open_dataset(day.strftime(f'{conf.emissions.CH4.prefix}.CH4.{reg}.%Y%m%d.nc'))
            emtot = em.to_array().sum('variable').values

            for itr in set(itrac):
                date.append(day)
                region.append(reg)
                obs.append(adj.tracer.values[itr].strip().decode())

                subset = itrac == itr
                sensi_trac = sensi[subset]
                _dmix = (emtot[ilats[subset], ilons[subset]] * sensi[subset]).sum()
                # if itr==ista:
                #     msg = f"@{sta}, {day.strftime('%Y-%m-%d')}, {reg}: dmix = {_dmix}, sensi_trac min/mean/max = " \
                #     f"{sensi_trac.min()}/{sensi_trac.mean()}/{sensi_trac.max()}"
                #     # print(msg)
                #     dmix_sta.append(_dmix)
                dmix.append(_dmix)
    # print(f"@{sta}, {runend}: sum(dmix_sta)={sum(dmix_sta)}")
    # Store everything in a common dataframe. Each row contains the contribution of one date and region to one specific obs
    fwd = DataFrame.from_dict({'obs': obs, 'region': region, 'date': date, 'mix': dmix})
    return fwd
