#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""interface to read and assemble footprints generated by TM5 adoint tracer run."""

#-- system packages
import sys
import os
from omegaconf import OmegaConf, DictConfig
from pathlib import Path
from collections import OrderedDict
from loguru import logger
from pandas import date_range, DataFrame, Series
from pandas import Timestamp, Timedelta, concat
import xarray as xr
import numpy as np
from numpy import zeros, tile
from numpy.typing import NDArray
from netCDF4 import Dataset, chartostring
import xesmf
from types import SimpleNamespace
#-- library packages
from tm5.gridtools import TM5Grids
from tm5.fitic import read_obs_table


#
#-- table of FIT-IC regions
#   - their will be one (global) instance for all queries
#   TODO: should not be hard-coded here!
#
region_table = OrderedDict()


def _init_region_table():
    global region_table
    if len(region_table)>0:
        return #-- should be already initialised
    #
    #-- create grid instances
    #
    glb_grid = TM5Grids.from_corners(west=-180, east=180, south=-90, north=90, dlon=6, dlat=4)
    eur_grid = TM5Grids.from_corners(west=-36, east=54, south=22, north=74, dlon=3, dlat=2)
    gns_grid = TM5Grids.from_corners(west=0, east=18, south=42, north=58, dlon=1, dlat=1)
    #
    #-- initial attributes (per region)
    #
    region_table['glb600x400'] = SimpleNamespace(
        grid=glb_grid,
        rlat=4, rlon=6,
        child='eur300x200', parent=None)
    region_table['eur300x200'] = SimpleNamespace(
        grid=eur_grid,
        rlat=2, rlon=3,
        child='gns100x100', parent='glb600x400')
    region_table['gns100x100'] = SimpleNamespace(
        grid=gns_grid,
        rlat=1, rlon=1,
        child=None, parent='eur300x200')
    #
    #-- extending attributes
    #   - 1D flattened arrays of coordinates
    #   - prepare for filtering out child domain within in parent
    #
    for reg,reg_info in region_table.items():
        grid = reg_info.grid
        area1D = grid.area.ravel()
        #
        lonmesh,latmesh = np.meshgrid(grid.lonc,grid.latc)
        region_table[reg].ng1D = grid.nlat*grid.nlon
        region_table[reg].lonc1D = lonmesh.ravel()
        region_table[reg].latc1D = latmesh.ravel()
        region_table[reg].area1D = area1D
        if reg_info.child!=None:
            grid_child = region_table[reg_info.child].grid
            #-- create mask array, 0 within child region and 1 elsewhere 
            damask = xr.DataArray(
                np.ones((grid.nlat, grid.nlon), dtype='i4'),
                dims = ('lat','lon'),
                coords = { 'lon' : grid.lonc,
                           'lat' : grid.latc },
                name = 'mask')
            lat_slice = slice(grid_child.south,grid_child.north)
            lon_slice = slice(grid_child.west,grid_child.east)
            damask.loc[dict(lat=lat_slice,lon=lon_slice)] = 0
            usemask = (damask.values==1).ravel()
            nguse = np.count_nonzero(usemask)
            # print(f"@{reg}, ngtot={usemask.size}, nguse={nguse}")
            region_table[reg].usemask = usemask
            region_table[reg].ng1D_clipped = nguse
            region_table[reg].lonc1D_clipped = lonmesh.ravel()[usemask]
            region_table[reg].latc1D_clipped = latmesh.ravel()[usemask]
            region_table[reg].area1D_clipped = area1D[usemask]
        #
        #-- HALO corrected 1D vectors
        #   - at all edges discarding the width of one parent grid-cell
        #
        if reg_info.parent==None: #-- glb600x400 [nothing to change]
            nohalo_mask = np.full((grid.nlat, grid.nlon), True)
            region_table[reg].ng1D_nohalo = region_table[reg].ng1D
            region_table[reg].lonc1D_nohalo = region_table[reg].lonc1D
            region_table[reg].latc1D_nohalo = region_table[reg].latc1D
            region_table[reg].area1D_nohalo = region_table[reg].area1D
            region_table[reg].nohalo_mask = nohalo_mask.ravel()
        else:
            grid_parent = region_table[reg_info.parent].grid
            dlon_parent = grid_parent.dlon
            dlat_parent = grid_parent.dlat
            nlon_halo = grid_parent.dlon//grid.dlon
            nlat_halo = grid_parent.dlat//grid.dlat
            msg = f"@{reg}, nlon/nlat = {grid.nlon}/{grid.nlat} " \
                f"nlon_halo/nlat_halo = {nlon_halo}/{nlat_halo}"
            logger.debug(msg)
            #-- create mask (value=False for grid-cells within HALO)
            nohalo_mask = np.full((grid.nlat, grid.nlon), False)
            nohalo_mask[nlat_halo:-nlat_halo,nlon_halo:-nlon_halo] = True
            msg = f"@{reg}, nohalo_mask.shape={nohalo_mask.shape}, np.count_nonzero(nohalo_mask)={np.count_nonzero(nohalo_mask)}"
            logger.debug(msg)
            lonmesh_nohalo = lonmesh[nlat_halo:-nlat_halo,nlon_halo:-nlon_halo]
            latmesh_nohalo = latmesh[nlat_halo:-nlat_halo,nlon_halo:-nlon_halo]
            area_nohalo = grid.area[nlat_halo:-nlat_halo,nlon_halo:-nlon_halo]
            region_table[reg].ng1D_nohalo = len(lonmesh_nohalo.ravel())
            region_table[reg].lonc1D_nohalo = lonmesh_nohalo.ravel()
            region_table[reg].latc1D_nohalo = latmesh_nohalo.ravel()
            region_table[reg].area1D_nohalo = area_nohalo.ravel()
            region_table[reg].nohalo_mask = nohalo_mask.ravel()


def regions1D_info( regions : list, remove_halo : bool = False, clip_child : bool = False ) -> SimpleNamespace:
    if remove_halo and clip_child:
        msg = f"options remove_halo and clip_child cannot be active at the same time"
        raise NotImplementedError(msg)
    if len(region_table)==0:
        msg = f"...initialise region table"
        logger.info(msg)
        _init_region_table()
    expected_region_list = [ list(region_table.keys()), ['glb600x400',] ]
    assert regions in expected_region_list, \
        f"region_list -->{region_list}<-- but supported -->{expected_region_list}<--"
    region_list = []
    lonc_list = []
    latc_list = []
    area_list = []
    ng = 0
    for reg in regions:
        reg_info = region_table[reg]
        grid = reg_info.grid
        if remove_halo:
            ng += reg_info.ng1D_nohalo
            region_list = region_list + [reg,]*reg_info.ng1D_nohalo
            lonc_list.append(reg_info.lonc1D_nohalo)
            latc_list.append(reg_info.latc1D_nohalo)
            area_list.append(reg_info.area1D_nohalo)
        elif clip_child:
            if reg=='gns100x100':
                ng += reg_info.ng1D
                region_list = region_list + [reg,]*reg_info.ng1D
                lonc_list.append(reg_info.lonc1D)
                latc_list.append(reg_info.latc1D)
                area_list.append(reg_info.area1D)
            else:
                ng += reg_info.ng1D_clipped
                region_list = region_list + [reg,]*reg_info.ng1D_clipped
                lonc_list.append(reg_info.lonc1D_clipped)
                latc_list.append(reg_info.latc1D_clipped)
                area_list.append(reg_info.area1D_clipped)
        else:
            ng += reg_info.ng1D
            region_list = region_list + [reg,]*reg_info.ng1D
            lonc_list.append(reg_info.lonc1D)
            latc_list.append(reg_info.latc1D)
            area_list.append(reg_info.area1D)
    #
    lonc1D = np.hstack(lonc_list)
    latc1D = np.hstack(latc_list)
    area1D = np.hstack(area_list)
    reg1D  = np.array(region_list)
    return SimpleNamespace(table=region_table, ng=ng, lonc1D=lonc1D, latc1D=latc1D, area1D=area1D, reg1D=reg1D)


def regiondomain_halo( region : str ) -> list:
    if len(region_table)==0:
        msg = f"...initialise region table"
        logger.info(msg)
        _init_region_table()
    #
    reginfo = region_table[region]
    lonmin,lonmax,latmin,latmax = reginfo.grid.domain
    #
    #-- drop the halo zone
    #
    if reginfo.parent!=None:
        dlon = region_table[reginfo.parent].grid.dlon
        dlat = region_table[reginfo.parent].grid.dlat
        lonmin = lonmin+dlon
        lonmax = lonmax-dlon
        latmin = latmin+dlat
        latmax = latmax-dlat
    return [lonmin,lonmax,latmin,latmax,]


def tm5emisdir_load_emissions2D( emisdir : str | Path, emis_prefix : str, day_range : date_range, regions : list, remove_halo : bool = True, clip_child : bool = False ) -> SimpleNamespace:
    """Read in daily emissions as prepared for TM5 for the selected temporal range
    and regions.
    The emissions array will be 2D with only one single dimension in the spatial domain,
    and concatenating the contributions from each region in the spatial domain as well.
    """
    # #
    # #-- make sure region table is set-up
    # #
    # if len(region_table)==0:
    #     msg = f"...initialise region table"
    #     logger.info(msg)
    #     _init_region_table()
    nday = len(day_range)
    #
    #-- get spatial information as 1D vector
    #
    domain1D_info = regions1D_info(regions, remove_halo=remove_halo, clip_child=clip_child)
    ng = domain1D_info.ng
    lonc1D = domain1D_info.lonc1D
    latc1D = domain1D_info.latc1D
    reg1D  = domain1D_info.reg1D
    region_table = domain1D_info.table
    msg = f"...preparing emissions for nday={nday} and ng={ng}"
    logger.info(msg)
    #
    #-- prepare emissions field
    #
    missval = -99999.
    emissions2D = np.full((nday,ng), missval)
    for iday,day in enumerate(day_range):
        emis_list = []
        for reg in regions:
            #-- TODO:: 'CH4' is still hard-coded here!
            fpath = Path(day.strftime(f'{emis_prefix}.CH4.{reg}.%Y%m%d.nc'))
            if not fpath.exists():
                msg = f"expected emissions file ***{str(fpath)}*** not found on system."
                raise FileNotFoundError(msg)
            #
            #-- open emissions file for current region
            #
            em = xr.open_dataset(fpath)
            #
            #-- sum-up total emissions
            #
            emtot = em.to_array().sum('variable').values
            #
            #-- turn lat/lon into 1D vector (lat major ordering)
            #
            emtot = emtot.ravel()
            ngtot = len(emtot)
            #
            #-- potentially set emissions to zero for grid-cells within child domain
            #
            if remove_halo:
                msk = region_table[reg].nohalo_mask
                emtot = emtot[msk]
                if iday==0:
                    msg = f"@{reg}/{day}: applied remove_halo mask reduces #gridcells from " \
                        f"{ngtot} to {len(emtot)}"
                    logger.debug(msg)
            elif clip_child:
                #--
                if reg=='gns100x100':
                    #-- *all* emissions from innermost domain
                    assert len(emtot)==region_table[reg].ng1D
                else:
                    #-- contributions from child domain excluded
                    msk = region_table[reg].usemask
                    emtot = emtot[msk]
                    assert len(emtot)==region_table[reg].ng1D_clipped
            emis_list.append(emtot)
        #-- add concatenated emissions
        emissions2D[iday,:] = np.hstack(emis_list)
    #-- consistency: emissions should be filled completely!
    assert np.count_nonzero(emissions2D==missval)==0
    
    return SimpleNamespace(emis2D=emissions2D,
                           reg1D=reg1D, lonc1D=lonc1D, latc1D=latc1D,
                           emisdir=emisdir)


def tm5rundir_obstable( outpath : str | Path, drop_missing_value : bool = False ) -> DataFrame:
    yamlfile = Path(outpath) / 'tm5.yaml'
    if not yamlfile.exists():
        msg = f"yaml configuration file ***{str(yamlfile)}*** not found on system."
        raise FileNotFoundError(msg)
    conf = OmegaConf.load(yamlfile)

    # Load the observations table
    obs_table = read_obs_table(conf.observations.file, drop_missing_value).set_index('obsid')
    return obs_table


def tm5rundir_iniconc_1obs( outpath : str | Path, obs_info : Series ) -> SimpleNamespace:
    """
    """
    yamlfile = Path(outpath) / 'tm5.yaml'
    if not yamlfile.exists():
        msg = f"yaml configuration file ***{str(yamlfile)}*** not found on system."
        raise FileNotFoundError(msg)
    dconf = OmegaConf.load(yamlfile)
    reglist = dconf.run.regions
    #
    #--
    #
    sta_tracer = obs_info.tracer
    sta_id     = obs_info.station_id
    sta_lon    = obs_info.lon
    sta_lat    = obs_info.lat
    #-- determine innermost zoom region of station
    sta_region = None
    for reg in reglist[::-1]:
        lonw,lone = dconf.regions[reg].lons[:2]
        lats,latn = dconf.regions[reg].lats[:2]
        if lonw<=sta_lon<=lone and lats<=sta_lat<=latn:
            sta_region = reg
            break
    # msg = f"sta_id={sta_id} detected in region -->{sta_region}<--"
    # print(msg)
    #
    #-- read from point output file
    #   - group structure in file is <region>/<tracer>
    #
    outp_file = Path(outpath) / 'point' / 'point_output.nc4'
    if not outp_file.exists():
        msg = f"expected point output file ***{str(outp_file)}*** not found."
        raise FileNotFoundError(msg)
    else:
        msg = f"...@{sta_id}, reading initial concentration from ==>{str(outp_file)}<=="
        logger.debug(msg)
    #
    #-- select region/tracer for current observation
    #
    outp = xr.open_dataset(outp_file, group=f'{sta_region}/{sta_tracer}').to_dataframe()
    #
    #-- extract only selected station
    #
    sta_outp = outp.set_index('station_id').loc[sta_id,:]
    # msg = f"@{outpath.name}, sta_id={sta_id} conc={sta_outp.mixing_ratio}"
    # print(msg)
    return SimpleNamespace(point_output=sta_outp, conc=sta_outp.mixing_ratio, nsamples=sta_outp.nsamples, averaging_time=sta_outp.averaging_time)


def tm5rundir_emissions2D( outpath : str | Path, trange : date_range = None,
                           emis_prefix : str = None,
                           remove_halo : bool = True, clip_child : bool = False, host : str = 'cosmos' ) -> SimpleNamespace:
    """
    """
    if remove_halo and clip_child:
        msg = f"options remove_halo and clip_child cannot be active at the same time"
        raise NotImplementedError(msg)
    yamlfile = Path(outpath) / 'tm5.yaml'
    if not yamlfile.exists():
        msg = f"yaml configuration file ***{str(yamlfile)}*** not found on system."
        raise FileNotFoundError(msg)
    dconf = OmegaConf.load(yamlfile)
    if not 'host' in dconf:
        dconf.host = dconf[host]
    emisdir = dconf.run.paths.emissions
    # print(f"@{outpath}, *****{emisdir}*****")
    # sys.exit(0)
    regions = dconf.run.regions
    if trange is None:
        tstart = Timestamp(dconf.run.start)
        tend   = Timestamp(dconf.run.end)
        trange = date_range(tstart, tend, freq='1d')
    emis_prefix_rundir = dconf.emissions.CH4.prefix
    if emis_prefix!=None:
        msg = f"TM5 rundir has emis_prefix -->{emis_prefix_rundir}<--, which will be explicitly " \
            f"overwritten to -->{emis_prefix}<--"
        logger.warning(msg)
    else:
        emis_prefix = emis_prefix_rundir

    return tm5emisdir_load_emissions2D(emisdir, emis_prefix, trange, regions, remove_halo=remove_halo, clip_child=clip_child)


def tm5rundir_jacobian3D( outpath : str | Path, emisday_range : date_range = None,
                          obsid : str|list|None = None,
                          remove_halo : bool = True, clip_child : bool = False ) -> NDArray:
    """
    Reads in the sensitivity (or Jacobian) from ***one single TM5 adjoint run***,
    which provides the sensitivities of CH4 concentrations (at multiple stations) with respect
    to all daily emissions from simulation start to the observational day.
    
    We store these sensitivities conceptionally in an array (nobs,nemis),
    where nobs quantifies the number of stations, while emission days *and* emission grid-cells
    are combined into a single 1D vector of 'nemis' elements.
    Ordering of emission time and location in this 1D vector is as follows
    - day1
      - reg1 (flattened)
      - reg2 (flattened)
      - reg3 (flattened)
    - day2
      - reg1 (flattened)
      .
      .
      .
    """
    if remove_halo and clip_child:
        msg = f"options remove_halo and clip_child cannot be active at the same time"
        raise NotImplementedError(msg)
    #
    #-- load footprints into dataframe, plus ancillary information
    #
    fpinfo = tm5_fitic_adjoint_corrected_halos(outpath, emisday_range)
    footp_df = fpinfo.data
    obsids   = fpinfo.obsids
    days     = fpinfo.days
    regions  = fpinfo.regions
    nobs = len(obsids)
    nemisday = len(days)
    msg = f"...origin footprint data read, nfootp={len(footp_df)} for nobs/nemisday = {nobs}/{nemisday}"
    # msg = f"...after tm5_fitic_adjoint_corrected_halos obsids -->{obsids}<--"
    # logger.debug(msg)
    # ### DEBUGGING
    # footp_df.to_csv("footprint_dataframe.csv")
    if type(obsid)==str:
        obsid = [obsid,]
    if obsid!=None:
        msg = f"...extract only for observation -->{obsid}<--"
        logger.info(msg)
        #-- position of obs. identifier (location) in list of tracers/obs
        itrac_list = [ obsids.index(_) for _ in obsid ]
        nobsout = len(itrac_list)
        cnd_obs = footp_df['itrac'].isin(itrac_list)
        footp_df = footp_df.loc[cnd_obs,:]
        msg = f"......{len(footp_df)} selected footprints."
        logger.info(msg)
        # footp_df.to_csv(f"footprint_dataframe_selected-obsids.csv")
        # msg = f"......itrac_list -->{itrac_list}<--"
        # logger.debug(msg)
        # for iday in range(nemisday):
        #     for reg in region_table.keys():
        #         cnd = (footp_df.loc[:,'itime']==iday)&(footp_df.loc[:,'region']==reg)
        #         dd = footp_df.loc[cnd,:]
        #         sens = dd.loc[:,'value'].values
        #         msg = f"@{obsid}, {days[iday].strftime('%Y%m%d')}, {reg}: " \
        #             f"sens_values min/mean/max = {sens.min()}/{sens.mean()}/{sens.max()}"
        #         print(msg)
    else:
        itrac_list = np.arange(nobs)
        nobsout = nobs
    #
    #-- get spatial information as 1D vector
    #
    domain1D_info = regions1D_info(regions, remove_halo=remove_halo, clip_child=clip_child)
    ng = domain1D_info.ng
    lonc1D = domain1D_info.lonc1D
    latc1D = domain1D_info.latc1D
    reg1D  = domain1D_info.reg1D
    msg = f"...preparing Jacobian for emissions for {nobs} observation locations, " \
        f" {nemisday} emission days and ng={ng} emission grid-cells (per day)."
    logger.info(msg)
    #
    #-- initialise Jacobian to zero
    #
    jacobian3D = zeros((nobsout,nemisday,ng))
    #
    #-- fill
    #
    for iobs,itrac in enumerate(itrac_list):
        cur_obsid = obsids[itrac]
        cnd_obs = footp_df.loc[:,'itrac']==itrac
        df = footp_df.loc[cnd_obs,:]
        # msg = f"...restricted to {cur_obsid} yields {len(df)} entries"
        # logger.debug(msg)
        for iday in range(nemisday):
            #-- collect sensitivity contributions from all regions
            jac_list = []
            cnd_day = df.loc[:,'itime']==iday
            df_day = df.loc[cnd_day,:]
            # msg = f"...restricted to {days[iday].strftime('%Y%m%d')} yields {len(df_day)} entries"
            # logger.debug(msg)
            for reg in regions:
                # print(f"@{reg}\n", df.head())
                cnd_reg = df_day.loc[:,'region']==reg
                df_reg = df_day.loc[cnd_reg,:]
                # msg = f"...restricted to {reg} yields {len(df_reg)} entries"
                # logger.debug(msg)
                grid = region_table[reg].grid
                # print(f"@{reg}, nlat/nlon = {grid.nlat}/{grid.nlon}")
                sens = zeros((grid.nlat, grid.nlon))
                sens[df_reg.ilat, df_reg.ilon] = df_reg.value
                #
                sens = sens.ravel()
                # msg = f"@itrac={itrac}/iday={iday}/{reg}, sens min/mean/max = " \
                #     f"{sens.min()}/{sens.mean()}/{sens.max()}"
                # print(msg)
                msk = None
                if remove_halo and clip_child:
                    msk = region_table[reg].nohalo_mask & region_table[reg].usemask
                elif remove_halo:
                    msk = region_table[reg].nohalo_mask
                elif clip_child:
                    msk = region_table[reg].usemask
                if not msk is None:
                    sens = sens[msk]
                jac_list.append(sens)
                # msg = f"@{cur_obsid}/iday={iday}/{reg}: sens min/mean/max = " \
                #     f"{sens.min()}/{sens.mean()}/{sens.max()}"
                # logger.info(msg)
            #
            jacobian3D[iobs,iday,:] = np.hstack(jac_list)
    #
    return SimpleNamespace(jac3D=jacobian3D, days=days, obsids=obsids,
                           reg1D=reg1D, lonc1D=lonc1D, latc1D=latc1D)


def tm5_fitic_adjoint_corrected_halos( outpath : str|Path, emisday_range : date_range = None) -> SimpleNamespace:
    """Function to read and collect footprint information from one TM5 adjoint run
    for selected period of time into a pandas dataframe for further processing.
    outpath must be the toplevel output directory of the TM5 forward and adjoint run,
    that also contains the rc-configuration files.
    The dataframe will contain 

    Currently it is expected that the simulation was carried on the FIT-IC spatial zoom
    domain.

    This routine handles the HALOs of the two inner zoom domains (eur300x200, gns100x100).
    """
    yamlfile = Path(outpath) / 'tm5.yaml'
    if not yamlfile.exists():
        msg = f"yaml configuration file ***{str(yamlfile)}*** not found on system."
        raise FileNotFoundError(msg)
    dconf = OmegaConf.load(yamlfile)
    #
    #-- get name of tracer/obsids
    #
    # MVO-ATTENTION::
    # - for the zoom footprint simulations the the ingoing obs file
    #   contained always *all* stations - also in case if no actual observation
    #   was available for a particular day.
    # - Thus, for the proper indexing below, we *MUST NOT* drop
    #   those here!
    #   
    obs_table = tm5rundir_obstable(outpath, drop_missing_value=False)
    tracer = list(obs_table.index)
    
    #
    #-- collect adjoint emission files
    #
    adjemis_dir = Path(outpath) / 'adjemis'   
    emisfile_list = sorted(list(adjemis_dir.glob(f"adjemis.*.nc")))
    #
    #-- determine regions
    #
    if len(region_table)==0:
        msg = f"...initialise region table"
        logger.info(msg)
        _init_region_table()
    #
    region_list = dconf.run.regions
    #
    #-- for now we handle
    #   - ['glb600x400', 'eur300x200', 'gns100x100']  --> 
    #   - ['glb600x400',]
    #
    expected_region_list = [ list(region_table.keys()), ['glb600x400',] ]
    assert region_list in expected_region_list, \
        f"region_list -->{region_list}<-- but supported -->{expected_region_list}<--"
    #
    #-- set temporal domain
    #
    if emisday_range is None:
        emisday_range = date_range(dconf.run.start, dconf.run.end, freq='1d')
    #
    #-- dictionary for collecting footprint results
    #
    footprints = { 'ilat':[],
                   'ilon':[],
                   'latc':[],  #-- only for diagnostics
                   'lonc':[],  #-- only for diagnostics
                   'itime':[],
                   'value':[],
                   'region':[],
                   'itrac':[]   }
    #
    #-- MVO-20260424:
    #   - dataasets in adjoint emissions files are written as long 1D arrays (dimension: point),
    #     variable 'int itrac(point)' provides index of associated tracer
    #   - Thus, there should be *no* need to loop along the tracer !?
    for iday, day in enumerate(emisday_range):
        for ireg, region in enumerate(region_list):
            fname = adjemis_dir / day.strftime(f'adjemis.{region}.%Y%m%d.nc')
            # Adjoint files are written only if needed, so it may not exist for a given day/region
            if not fname.exists():
                continue
            with Dataset(fname, 'r') as ds:
                ilat = ds['ilat'][:].data
                ilon = ds['ilon'][:].data
                itrac = ds['itrac'][:].data
                values = ds['values'][:].data
                lonc = ds['lon'][:].data
                latc = ds['lat'][:].data
                lonc = lonc[ilon]
                latc = latc[ilat]
                nfootp = len(ilat)
            # print(f"@{region},{day.strftime('%Y-%m-%d')}: " \
            #       f"ilon min/max={min(ilon)}/{max(ilon)}, " \
            #       f"ilat min/max={min(ilat)}/{max(ilat)}, ")
            #
            #-- halo correction
            #
            # if iday==0:
            #     nfootp = len(ilat)
            #     print(f"@{region},{day.strftime('%Y-%m-%d')}: #footprints={nfootp}")
            if region=='gns100x100':
                #
                #- on zonal and 
                #
                lonmin,lonmax,latmin,latmax = regiondomain_halo(region)
                cnd_lon = (lonc>=lonmin)&(lonc<=lonmax)
                cnd_lat = (latc>=latmin)&(latc<=latmax)
                cnd_nohalo = cnd_lon&cnd_lat
                # print(f"@{region},{day.strftime('%Y-%m-%d')}, nfootp prior/post filtering = " \
                #       f"{nfootp}/{np.count_nonzero(cnd_nohalo)}")
            elif region=='eur300x200':
                #-- initial approach:
                #   (1) restrict to halo corrected domain of region
                #   (2) remove parts from the inner-most zoom domain
                #
                # lonmin1,lonmax2,latmin1,latmax2 = regiondomain_halo(region)
                # lonmax1,lonmin2,latmax1,latmin2 = regiondomain_halo(region_table[region].child)
                # cnd_lon = ((lonc>=lonmin1)&(lonc<=lonmax1))|((lonc>=lonmin2)&(lonc<=lonmax2))
                # cnd_lat = ((latc>=latmin1)&(latc<=latmax1))|((latc>=latmin2)&(latc<=latmax2))
                # cnd_nohalo = cnd_lon&cnd_lat
                # MVO: 2026-04-29, Guillaume confirmed that removal of "inner" part
                #                  is handled within TM5
                lonmin,lonmax,latmin,latmax = regiondomain_halo(region)
                cnd_lon = (lonc>=lonmin)&(lonc<=lonmax)
                cnd_lat = (latc>=latmin)&(latc<=latmax)
                cnd_nohalo = cnd_lon&cnd_lat
                # print(f"@{region},{day.strftime('%Y-%m-%d')}, nfootp prior/post filtering = " \
                #       f"{nfootp}/{np.count_nonzero(cnd_nohalo)}")
            elif region=='glb600x400':
                #-- initial approach:
                #   (1) restrict to halo corrected domain of region
                #   (2) remove parts from the inner-most zoom domain
                #
                # lonmin1,lonmax2,latmin1,latmax2 = regiondomain_halo(region)
                # lonmax1,lonmin2,latmax1,latmin2 = regiondomain_halo(region_table[region].child)
                # cnd_lon = ((lonc>=lonmin1)&(lonc<=lonmax1))|((lonc>=lonmin2)&(lonc<=lonmax2))
                # cnd_lat = ((latc>=latmin1)&(latc<=latmax1))|((latc>=latmin2)&(latc<=latmax2))
                # cnd_nohalo = cnd_lon&cnd_lat
                # print(f"@{region},{day.strftime('%Y-%m-%d')}, nfootp prior/post filtering = " \
                #       f"{nfootp}/{np.count_nonzero(cnd_nohalo)}")
                # MVO: 2026-04-29, Guillaume confirmed that removal of "inner" part
                #                  is handled within TM5
                # => for the global domain there are no halos to correct!
                # => all collected footprints are taken
                cnd_nohalo = np.full(len(ilat), True)
            ##
            idxs_nohalo = np.where(cnd_nohalo)
            ilat = ilat[idxs_nohalo]
            ilon = ilon[idxs_nohalo]
            itrac = itrac[idxs_nohalo]
            values = values[idxs_nohalo]
            lonc = lonc[idxs_nohalo]
            latc = latc[idxs_nohalo]
            nfootp = len(ilat)
            # #
            # #-- cbw_207 at second position
            # #
            # icbw = np.where(itrac==1)
            # vcbw = values[icbw]
            # msg = f"DEBUG@cbw_207, {day.strftime('%Y-%m-%d')}, {region}: " \
            #     f"values min/mean/max = {vcbw.min()}/{vcbw.mean()}/{vcbw.max()}"
            # print(msg)
            # if iday==0:
            #     msg = f"@{region},{day.strftime('%Y-%m-%d')}: after halo-correction " \
            #         f"remaining footprints={len(idxs_nohalo[0])}"
            #     print(msg)

            footprints['ilat'].extend(ilat)
            footprints['ilon'].extend(ilon)
            footprints['latc'].extend(latc)
            footprints['lonc'].extend(lonc)
            footprints['itime'].extend([iday] * nfootp)
            footprints['value'].extend(values)
            footprints['itrac'].extend(itrac)
            footprints['region'].extend([region] * nfootp)
    footprints = DataFrame.from_dict(footprints)
    # msg = f"...overall #footprints={len(footprints)}"
    # logger.info(msg)
    return SimpleNamespace(data=footprints, days=emisday_range, regions=region_list, obsids=tracer)


def jacobian_redistribute_glb6x4_to_avengers_zoom( ojac_6x4 : xr.DataArray, remove_halo : bool = True ) -> SimpleNamespace:
    """
    Re-distributing sensitivities (Jacobian) that were computed globally only at the
    coarse 6x4 degree resolution spatially to grid-cells as used in the AVENGERS
    3-level zoom configuration (glb6x4,eur3x2,gns1x1).
    Depending on the flag the HALO parts of the two inner domains may be dropped in
    the generated output Jacobian.
    The output Jacobian numpy array will have shape (nobs,ng), where nobs is the
    number of observational locations (where these include both, spatial and temporal
    dimension) and ng quantifies the number of emission grid-cells of the AVENGERS
    zoom configuration (where HALO parts of the inner domains have potentially been removed).
    """
    #
    #-- some consistency checks
    #
    expected_dims  = ('nobs','lat','lon')
    expected_units = ['ppb/(kgCH4/cell)', 'ppb/(kgCH4/cell/s)',]
    if ojac_6x4.dims!=expected_dims:
        msg = f"ojac_6x4 with unexpected dimensions -->{ojac_6x4.dims}<-- " \
            f"(expected: ==>{expected_dims}<==)"
        raise RuntimeError(msg)
    if not ojac_6x4.units in expected_units:
        msg = f"ojac_6x4 with unexpected dimensions -->{ojac_6x4.units}<-- " \
            f"(expected: ==>{expected_units}<==)"
    nobs,_nlat,_nlon = ojac_6x4.shape
    #
    #-- spatial information for the AVENGERS/FIT-IC zoom configuration
    #
    reginfo_avengers = regions1D_info(['glb600x400','eur300x200','gns100x100',], remove_halo=remove_halo)
    region_table = reginfo_avengers.table
    #
    #-- define global grids at the two finer resolutions
    #
    glb_6x4 = region_table['glb600x400'].grid
    eur_3x2 = region_table['eur300x200'].grid
    gns_1x1 = region_table['gns100x100'].grid
    glb_3x2 = TM5Grids.from_corners(west=-180, east=180, south=-90, north=90, dlon=3, dlat=2)
    glb_1x1 = TM5Grids.global1x1()
    #>> expecting input at 6x4 degree resolution
    if (_nlat,_nlon)!=(glb_6x4.nlat,glb_6x4.nlon):
        msg = f"ojac_6x4 with unexpected shape -->{(_nlat,_nlon)}<-- " \
            f"(expected: {(glb_6x4.nlat,glb_6x4.nlon)}"
        raise RuntimeError(msg)
    #
    #-- global 6x4 sensitivites [ppb/(kgCH4/cell)] --> [ppb/(kgCH4/m2)]
    #   -> nearest neighbour upscaling must happen in per-squaremeter units
    #
    ojac_6x4 = ojac_6x4 / glb_6x4.area
    #
    #-- conversion to global 1x1 (nearest neighbour)
    #
    _ds_glb1x1 = xr.Dataset(coords=dict(lon=glb_1x1.lonc, lat=glb_1x1.latc))
    regridder = xesmf.Regridder(ojac_6x4, _ds_glb1x1, method='nearest_s2d')
    #-- global 1x1 sensitivites [ppb/(kgCH4/m2)]
    ojac_1x1 = regridder(ojac_6x4)
    #-- global 1x1 sensitivites [ppb/(kgCH4/cell)] as required for output
    ojac_1x1 = ojac_1x1 * glb_1x1.area
    #
    #-- conversion to global 3x2 (nearest neighbour)
    #
    _ds_glb3x2 = xr.Dataset(coords=dict(lon=glb_3x2.lonc, lat=glb_3x2.latc))
    regridder = xesmf.Regridder(ojac_6x4, _ds_glb3x2, method='nearest_s2d')
    #-- global 3x2 sensitivites [ppb/(kgCH4/m2)]
    ojac_3x2 = regridder(ojac_6x4)
    #-- global 3x2 sensitivites [ppb/(kgCH4/cell)]
    ojac_3x2 = ojac_3x2 * glb_3x2.area
    #--
    msg = f"global sensitiviy sums over all observations and grid-cells for " \
        f"glb6x4/glb3x2/glb1x1 = {(ojac_6x4*glb_6x4.area).sum().values}/{ojac_3x2.sum().values}/{ojac_1x1.sum().values} [ppb/kgCH4]"
    logger.info(msg)
    #
    # (glb6x4) sensitivities within eur3x2 domain (excluding HALO) become zero
    #
    _lonmin = eur_3x2.west  + glb_6x4.dlon
    _lonmax = eur_3x2.east  - glb_6x4.dlon
    _latmin = eur_3x2.south + glb_6x4.dlat
    _latmax = eur_3x2.north - glb_6x4.dlat
    ojac_6x4.loc[dict(lat=slice(_latmin,_latmax), lon=slice(_lonmin,_lonmax))] = 0.
    #--
    ojac_6x4 = ojac_6x4.values.reshape(nobs,glb_6x4.ng)
    #
    # (eur3x2) - restrict global 3x2 to eur_3x2
    #
    _lon3x2 = (ojac_3x2.lon>=eur_3x2.west) & \
        (ojac_3x2.lon<=eur_3x2.east)
    _lat3x2 = (ojac_3x2.lat>=eur_3x2.south) & \
        (ojac_3x2.lat<=eur_3x2.north)
    ojac_3x2 = ojac_3x2.sel(lon=_lon3x2,lat=_lat3x2)
    #
    # (eur3x2) - zero out domain covered by innermost zoom (excluding HALO)
    #
    _lonmin = gns_1x1.west + glb_3x2.dlon
    _lonmax = gns_1x1.east - glb_3x2.dlon
    _latmin = gns_1x1.south + glb_3x2.dlat
    _latmax = gns_1x1.north - glb_3x2.dlat
    ojac_3x2.loc[dict(lat=slice(_latmin,_latmax), lon=slice(_lonmin,_lonmax))] = 0.
    #
    # (eur3x2) - turn lat/lon into 1D vector
    #
    ojac_3x2 = ojac_3x2.values.reshape(nobs,eur_3x2.ng)
    #
    # (eur3x2) - either restrict to nohalo part of domain
    #          - or set HALO part to zero
    #
    nohalo_mask = region_table['eur300x200'].nohalo_mask
    if remove_halo:
        ojac_3x2 = ojac_3x2[:,nohalo_mask]
    else:
        ojac_3x2[:,~nohalo_mask] = 0.
    #
    # (gns1x1) - restrict global 1x1 to gns1x1
    #
    _lon1x1 = (ojac_1x1.lon>=gns_1x1.west) & \
        (ojac_1x1.lon<=gns_1x1.east)
    _lat1x1 = (ojac_1x1.lat>=gns_1x1.south) & \
        (ojac_1x1.lat<=gns_1x1.north)
    ojac_1x1 = ojac_1x1.sel(lon=_lon1x1,lat=_lat1x1)
    #
    # (gns1x1) - turn lat/lon into 1D vector
    #
    ojac_1x1 = ojac_1x1.values.reshape(nobs,gns_1x1.ng)
    #
    # (gns1x1) - either restrict to nohalo part of domain
    #          - or set HALO part to zero
    #
    nohalo_mask = region_table['gns100x100'].nohalo_mask
    if remove_halo:
        ojac_1x1 = ojac_1x1[:,nohalo_mask]
    else:
        ojac_1x1[:,~nohalo_mask] = 0.
    #
    #-- concat domain contributions along rows
    #
    ojac_out = np.concatenate((ojac_6x4,ojac_3x2,ojac_1x1), axis=1)
    #-- update ng (number of grid-cells now extended)
    _nobs,ng = ojac_out.shape
    if ng!=reginfo_avengers.ng:
        msg = f"extended Jacobian has shape nobs/ng = {_nobs}/{ng}, " \
            f"but ng={reginfo_avengers.ng} was expected."
        raise RuntimeError(msg)
    emis_lonc1D = reginfo_avengers.lonc1D
    emis_latc1D = reginfo_avengers.latc1D
    emis_reg1D  = reginfo_avengers.reg1D

    return SimpleNamespace(jacobian=ojac_out, lonc1D=emis_lonc1D, latc1D=emis_latc1D, reg1D=emis_reg1D)


def emisvector_to_global1x1( filepath_emis : str | Path, varname : str = 'emission', tosqm : bool = False ) -> SimpleNamespace:
    """Function that remaps a 1D emission vector used within the FIT-IC
    inversion system back to global gridded emissions at 1x1 degree resolution.
    """

    #
    #-- open 1D emissions vector file
    #
    if not Path(filepath_emis).exists():
        msg = f"prior emissions file ***{filepath_emis}*** not found!"
        raise FileNotFoundError(msg)
    dsemis = Dataset(filepath_emis)
    #
    #-- setup current FIT-IC region table
    #
    if len(region_table)==0:
        msg = f"...initialise region table"
        logger.info(msg)
        _init_region_table()
    regions_expect = list(region_table.keys())
    #
    #-- 
    #
    ng = dsemis.dimensions['ng'].size
    reg1D = dsemis['/region'][:]
    reg1D_uniq = np.unique(reg1D)
    if len(reg1D_uniq)!=len(regions_expect):
        msg = f"...detected unexpected regions ***{reg1D_uniq}***"
        raise RuntimeError(msg)
    elif not set(reg1D_uniq)==set(regions_expect):
        msg = f"...detected unexpected regions ***{reg1D_uniq}***"
        raise RuntimeError(msg)
    msg = f"...emissions vector is for regions -->{regions_expect}<--"
    logger.info(msg)
    #
    #-- load emissions
    #
    ncemis = dsemis[f"/{varname}"]
    try:
        emis_units = ncemis.units
    except AttributeError:
        msg = f"expected attribute -->{units}<-- missing for variable 'emissions'"
        raise AttributeError(msg)
    #
    #-- initialise output on 1x1 global grid
    #
    grid_glb1x1 = TM5Grids.from_corners(west=-180, east=180, south=-90, north=90, dlon=1, dlat=1)
    emis_glb1x1 = xr.DataArray(
        zeros((grid_glb1x1.nlat, grid_glb1x1.nlon)),
        dims=('lat','lon'),
        coords = {'lon': grid_glb1x1.lonc, 'lat': grid_glb1x1.latc },
        attrs = {'units' : emis_units}
    )
    #
    #-- loop over regions from outer to inner (order matters!)
    #
    emis_results = SimpleNamespace(table_native={}, table_1x1={})
    for reg in regions_expect:
        # print(f"*****{reg}*****")
        rlat, rlon = region_table[reg].rlat, region_table[reg].rlon
        grid = region_table[reg].grid
        nlat, nlon = grid.nlat, grid.nlon
        #
        #-- restrict to grid-cells within current region
        #
        cnd_reg = (reg1D==reg)
        ngreg = np.count_nonzero(cnd_reg)
        if ngreg!=region_table[reg].ng1D:
            msg = f"...@{reg}, unexpected number of grid-cells in 1D vector, " \
                f"expected={region_table[reg].ng1D} found={ngreg}"
            raise RuntimeError(msg)
        #
        #-- remap 1D emissions field
        #
        if ncemis.dimensions==('nmon','ng'):
            #-- handling temporal dimension not ready yet!!
            msg = f"temporal dimension in emissions not yet supported!"
            raise NotImplementedError(msg)
            emis_data = ncemis[:][:,cnd_reg]
            nmon,_ng = emis_data.shape
            daemis = xr.DataArray(
                emis_data = emis_data.reshape(nt,grid.nlat,grid.nlon),
                dims=('time','lat','lon'),
                coords = {'lon': grid.lonc, 'lat': grid.latc, 'time': np.arange(1,nmon+1)  }
            )
        elif ncemis.dimensions==('ng',):
            emis_data = ncemis[:][cnd_reg]
            daemis = xr.DataArray(
                emis_data.reshape(grid.nlat,grid.nlon),
                dims=('lat','lon'),
                coords = {'lon': grid.lonc, 'lat': grid.latc },
                attrs = { 'units': emis_units}
            )
            emis_results.table_native[reg] = daemis
        else:
            raise RuntimeError(f"unexpected dimensions {ncemis.dimensions}")
        #
        #-- spatial domain of current region
        #
        lat_slice = slice(grid.south,grid.north)
        lon_slice = slice(grid.west,grid.east)
        #
        #-- no need to clip child part of current region
        #   since this is overwritten by the child emissions anyhow
        #
        if reg=='gns100x100':
            emis_glb1x1.loc[dict(lat=lat_slice,lon=lon_slice)] = daemis[:]
        else:
            #
            #-- upscale to 1x1
            #   - equally distributing emissions onto 1x1 grid-cells
            #     that belong to the same parent grid-cells
            #
            grid_1x1 = TM5Grids.from_corners(west=grid.west, east=grid.east, south=grid.south, north=grid.north, dlon=1, dlat=1)
            nscale = rlat*rlon
            emis_in = emis_data.reshape(nlat,nlon)
            #
            #-- upscale to 1 by 1 degree (nlat*rlat,nlon*rlon)
            #
            emis_data_1x1 = np.repeat(emis_in, rlon, axis=1).repeat(rlat, axis=0)
            # #
            # #-- MVO-TODO::still a poor man's solution here with explict looping for the upscaling!!
            # #             ...ths was done in a hurry with lack of time for smarter solution...
            # #
            # emis_data_1x1 = zeros((nlat*rlat,nlon*rlon))
            # for iilat in range(nlat*rlat):
            #     ilat = iilat//rlat
            #     for iilon in range(nlon*rlon):
            #         ilon = iilon//rlon
            #         emis_data_1x1[iilat,iilon] = emis_in[ilat,ilon]
            # if np.all(emis_data_1x1==emis_data_1x1x):
            #     msg = f"*****fast upscaling with numpy.repeat successfull*****"
            #     logger.info(msg)
            # else:
            #     msg = f"...issues with slow vs fast upscaling emissions."
            #     raise RuntimeError(msg)
            daemis_1x1 = xr.DataArray(
                emis_data_1x1,
                dims=('lat','lon'),
                coords = {'lon': grid_1x1.lonc, 'lat': grid_1x1.latc},
                attrs = { 'units': emis_units}
                )
            emis_results.table_1x1[reg] = daemis_1x1
            # print(f"@{reg}, totemis daemis/daemis_1x1 {daemis.sum().values}/{daemis_1x1.sum().values}")
            #
            #-- insert domain emissions into global 1x1 emissions data
            #
            emis_glb1x1.loc[dict(lat=lat_slice,lon=lon_slice)] = daemis_1x1[:]
    #--
    dsemis.close()
    #
    #-- unit conversion
    #
    if tosqm and emis_units=='kgCH4/cell':
        emis_glb1x1 = emis_glb1x1 / grid_glb1x1.area
        emis_glb1x1.attrs['units'] = 'kgCH4/m2'
    #
    #-- add to returned namespace
    #
    emis_results.emis_glb1x1 = emis_glb1x1
    emis_results.grid_glb1x1 = grid_glb1x1

    return emis_results


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#
#          d e p r e c e a t e d   m e t h o d s
#
#--  to be removed soon
#
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
def tm5rundir_emissions1D( outpath : str | Path, trange : date_range = None, host : str = 'cosmos') -> SimpleNamespace:
    """
    """
    yamlfile = Path(outpath) / 'tm5.yaml'
    if not yamlfile.exists():
        msg = f"yaml configuration file ***{str(yamlfile)}*** not found on system."
        raise FileNotFoundError(msg)
    dconf = OmegaConf.load(yamlfile)
    if not 'host' in dconf:
        dconf.host = dconf[host]
    emisdir = dconf.run.paths.emissions
    # print(f"@{outpath}, *****{emisdir}*****")
    # sys.exit(0)
    regions = dconf.run.regions
    if trange is None:
        tstart = Timestamp(dconf.run.start)
        tend   = Timestamp(dconf.run.end)
        trange = date_range(tstart, tend, freq='1d')
    # msg = f"emission directory ***{emisdir}***, regions -->{regions}<-- " \
    #     f"trange first/last = {trange[0]}/{trange[-1]}"
    # print(msg)
    #
    #-- reformat collected emissions values to 1D array
    #   ordering:
    #   - emisday1
    #     - grid-cells glb600x400 (flattened)
    #     - grid-cells eur300x200 (flattened)
    #     - grid-cells gns100x100 (flattened)
    #   - emisday2
    #     - grid-cells glb600x400 (flattened)
    #   .
    #   .
    #   .
    emissions_list = []
    iday_list = []
    region_list = []
    for iday,day in enumerate(trange):
        for reg in regions:
            #-- TODO:: 'CH4' is hard-coded here!
            fpath = Path(day.strftime(f'{dconf.emissions.CH4.prefix}.CH4.{reg}.%Y%m%d.nc'))
            if not fpath.exists():
                msg = f"expected emissions file ***{str(fpath)}*** not found on system."
                raise FileNotFoundError(msg)
            em = xr.open_dataset(fpath)
            #-- sum-up total emissions
            emtot = em.to_array().sum('variable').values
            #-- turn 2D spatial part into 1D
            emtot = emtot.ravel()
            nemis = len(emtot)
            emissions_list.append(emtot)
            iday_list.append(np.full((nemis,), iday, dtype='i4'))
            region_list.append(np.array([reg,]*nemis))
    #-- stack into single 1D array
    emissions1D = np.hstack(emissions_list)
    iday1D = np.hstack(iday_list)
    region1D = np.hstack(region_list)
    return SimpleNamespace(emis1D=emissions1D, iday1D=iday1D, region1D=region1D, emisdir=emisdir)


def tm5rundir_jacobian2D( outpath : str | Path, trange : date_range = None, obsid : str|None = None ) -> NDArray:
    """
    Reads in the sensitivity (or Jacobian) for one observational day.
    
    will yield an array of shape jac(nobs,nemis)
    nemis comprises emissionday and emission location into a single 1D array of order
    - day1
      - reg1 (flattened)
      - reg2 (flattened)
      - reg3 (flattened)
    - day2
      - reg1 (flattened)
      .
      .
      .
    """
    #
    #-- load footprints into dataframe, plus ancillary information
    #
    fpinfo = tm5_fitic_adjoint_corrected_halos(outpath, trange)
    footp_df = fpinfo.data
    obsids   = fpinfo.obsids
    days     = fpinfo.days
    regions  = fpinfo.regions
    nobs = len(obsids)
    nday = len(days)
    msg = f"...footprint data read, nfootp={len(footp_df)} for nobs/nday = {nobs}/{nday}"
    logger.debug(msg)
    if obsid!=None:
        msg = f"...extract only for observation -->{obsid}<--"
        logger.info(msg)
        itrac = obsids.index(obsid) #-- position of obs. in list of tracers/obs
        cnd_obs = footp_df.loc[:,'itrac']==itrac
        footp_df = footp_df.loc[cnd_obs,:]
        msg = f"......{len(footp_df)} remaining footprints."
        logger.info(msg)
        itrac_list = [ obsids.index(obsid), ]
        # for iday in range(nday):
        #     for reg in region_table.keys():
        #         cnd = (footp_df.loc[:,'itime']==iday)&(footp_df.loc[:,'region']==reg)
        #         dd = footp_df.loc[cnd,:]
        #         sens = dd.loc[:,'value'].values
        #         msg = f"@{obsid}, {days[iday].strftime('%Y%m%d')}, {reg}: " \
        #             f"sens_values min/mean/max = {sens.min()}/{sens.mean()}/{sens.max()}"
        #         print(msg)
    else:
        itrac_list = np.arange(nobs)
    #
    #--
    #
    if len(region_table)==0:
        msg = f"...initialise region table"
        logger.info(msg)
        _init_region_table()
    #
    jacobian2D = None
    for itrac in itrac_list:
        cur_obsid = obsids[itrac]
        cnd_obs = footp_df.loc[:,'itrac']==itrac
        df = footp_df.loc[cnd_obs,:]
        # msg = f"...restricted to {cur_obsid} yields {len(df)} entries"
        # logger.debug(msg)
        jac_list = []
        for iday in range(nday):
            cnd_day = df.loc[:,'itime']==iday
            df_day = df.loc[cnd_day,:]
            # msg = f"...restricted to {days[iday].strftime('%Y%m%d')} yields {len(df_day)} entries"
            # logger.debug(msg)
            for reg in regions:
                # print(f"@{reg}\n", df.head())
                cnd_reg = df_day.loc[:,'region']==reg
                df_reg = df_day.loc[cnd_reg,:]
                # msg = f"...restricted to {reg} yields {len(df_reg)} entries"
                # logger.debug(msg)
                grid = region_table[reg].grid
                # print(f"@{reg}, nlat/nlon = {grid.nlat}/{grid.nlon}")
                sens = zeros((grid.nlat, grid.nlon))
                sens[df_reg.ilat, df_reg.ilon] = df_reg.value
                #
                sens = sens.ravel()
                msg = f"@itrac={itrac}/iday={iday}/{reg}, sens min/mean/max = " \
                    f"{sens.min()}/{sens.mean()}/{sens.max()}"
                print(msg)
                jac_list.append(sens)
        jac_obs = np.hstack(jac_list)
        if jacobian2D is None:
            jacobian2D = jac_obs.reshape(1,len(jac_obs))
        else:
            jacobian2D = np.vstack(jacobian2D, jac_obs)
    #
    return SimpleNamespace(jac2D=jacobian2D, days=days, obsids=obsids, regions=regions)

def load_adjoint_fitic_footprint(conf : DictConfig) -> SimpleNamespace:
    """Function to extract footprints from single TM5 adjoint run
    together with information of the temporal coverage of the emissions
    and the observation identifiers.

    Code is based on parts from the Jupyter notebook 'forward_footprints.ipynb' that
    Guillaume had prepared for initial inspection and visualisation of the footprints.
    """
    outpath = Path(conf.run.paths.output)/'adjemis'
    regions = conf.run.regions
    start = Timestamp(conf.run.start)
    end = Timestamp(conf.run.end)

    
    #
    #-- be carefull regarding potential limitations we still have...
    #
    if regions!=['glb600x400', 'eurnf300x200', 'gns100x100']:
        msg = f"currently only the FIT-IC spatial setup is supported, but found " \
            f"-->{regions}<-- as regions in the configuration file."
        raise NotImplementedError(msg)
    
    #
    #-- determine tracers
    #   -> adjoint emissions directory should contain files adjemis.<region>.%Y%m%d.nc
    #      (expected at daily temporal resolution),
    #      all for the equal list of tracers.
    #   -> we deliberatly extract them from the first file
    #   -> MVO-NOTE, 20260424:
    #      - what is named here "tracer" is actually the (unique) observation identifier
    #        (taken from the point departure file) ingested into the adoint TM5 run.
    emisfile_list = sorted(list(outpath.glob(f"adjemis.*.nc")))
    emisfile = emisfile_list[0]
    with Dataset(emisfile, 'r') as ds:
        msg = f"...reading tracer information from file ***{emisfile}***"
        logger.debug(msg)
        nobs = ds.dimensions['tracer'].size
        tracer = chartostring(ds['/tracer'][:])
        tracer = [ _.strip() for _ in tracer ]
    #
    #--
    #
    trange = list(date_range(conf.run.start, conf.run.end, freq='1d'))[:-1]
    nday = len(trange)

    footprints = { 'ilat':[],
                   'ilon':[],
                   'itime':[],
                   'value':[],
                   'region':[],
                   'itrac':[]   }
    coords_table = {}
    #-- MVO-20260424:
    #   - dataasets in adjoint emissions files are written as long 1D arrays (dimension: point),
    #     variable 'int itrac(point)' provides index of associated tracer
    #   - Thus, there should be *no* need to loop along the tracer !?
    #-- temporal range (simulation ends at last day 0:00, this day is (typically) not simulated!)
    for iday, day in enumerate(trange):
        for ireg, region in enumerate(regions):
            fname = outpath / day.strftime(f'adjemis.{region}.%Y%m%d.nc')
            # Adjoint files are written only if needed, so it may not exist for a given day/region
            if not fname.exists():
                continue
            with Dataset(fname, 'r') as ds:
                ilat = ds['ilat'][:].data
                ilon = ds['ilon'][:].data
                itrac = ds['itrac'][:].data
                values = ds['values'][:].data
                lonc = ds['lon'][:].data
                latc = ds['lat'][:].data
            ndat = len(ilat)

            footprints['ilat'].extend(ilat)
            footprints['ilon'].extend(ilon)
            footprints['itime'].extend([iday] * ndat)
            footprints['value'].extend(values)
            footprints['itrac'].extend(itrac)
            footprints['region'].extend([region] * ndat)
            #-- store spatial coordinates for region (only once)
            if not region in coords_table:
                coords_table[region] = (lonc,latc)
    # for itrac in range(ntracer):
    #     for iday, day in enumerate(date_range(start, end, freq='d')):
    #         for ireg, region in enumerate(regions):
    #             fname = outpath / day.strftime(f'adjemis.{region}.%Y%m%d.nc')
    #             # Adjoint files are written only if needed, so it may not exist for a given day/region
    #             if not fname.exists():
    #                 continue
    #             with Dataset(fname, 'r') as ds:
    #                 ilat = ds['ilat'][:].data
    #                 ilon = ds['ilon'][:].data
    #                 itrac = ds['itrac'][:].data
    #                 values = ds['values'][:].data
    #                 lonc = ds['lon'][:].data
    #                 latc = ds['lat'][:].data
    #             ndat = len(ilat)

    #             footprints['ilat'].extend(ilat)
    #             footprints['ilon'].extend(ilon)
    #             footprints['itime'].extend([iday] * ndat)
    #             footprints['value'].extend(values)
    #             footprints['itrac'].extend(itrac)
    #             footprints['region'].extend([region] * ndat)
    #             #-- store spatial coordinates for region (only once)
    #             if not region in coords_table:
    #                 coords_table[region] = (lonc,latc)
    footprints = DataFrame.from_dict(footprints)

    # Correct the halos:
    r2 = footprints[footprints.region == 'eur300x200']
    # print("r2.ilon=",r2.ilon.values)
    # print("r2.ilat=",r2.ilat.values)
    footprints.loc[footprints.region == 'eur300x200', 'ilon'] = r2.ilon.values - 2
    footprints.loc[footprints.region == 'eur300x200', 'ilat'] = r2.ilat.values - 2
    r3 = footprints[footprints.region == 'gns100x100']
    # print("r3.ilon=",r3.ilon.values)
    # print("r3.ilat=",r3.ilat.values)
    footprints.loc[footprints.region == 'gns100x100', 'ilon'] = r3.ilon.values - 3
    footprints.loc[footprints.region == 'gns100x100', 'ilat'] = r3.ilat.values - 2

    
    # ------------------
    # Reproject the eur3x2 data on a 1x1 grid
    eur_west, eur_east = conf.regions['eur300x200'].lons[:2]
    eur_south, eur_north = conf.regions['eur300x200'].lats[:2]
    fpreg = footprints[footprints.region == 'eur300x200']
    grid0 = TM5Grids.from_corners(west=eur_west+6, east=eur_east-6, south=eur_south+4, north=eur_north-4, dlon=3, dlat=2)
    grid1 = TM5Grids.from_corners(west=eur_west+6, east=eur_east-6, south=eur_south+4, north=eur_north-4, dlon=1, dlat=1)

    # Duplicate the points
    rlon, rlat = 3, 2
    # print(f"#ilat={len(fpreg.ilat.values)}, #ilon={len(fpreg.ilon.values)}")
    # x = tile(fpreg.value.values, (rlat, rlon, 1))
    # print(f"x.shape={x.shape}")
    # x = x.reshape(-1)
    # print(f"x.shape={x.shape}")
    ilat = tile(fpreg.ilat.values * rlat, (rlat, rlon, 1))
    ilon = tile(fpreg.ilon.values * rlon, (rlat, rlon, 1))
    values = tile(fpreg.value.values, (rlat, rlon, 1)).reshape(-1)
    itime = tile(fpreg.itime.values, (rlat, rlon, 1)).reshape(-1)
    itrac = tile(fpreg.itrac.values, (rlat, rlon, 1)).reshape(-1)

    # Adjust the indices
    for jj in range(rlat):
        ilat[jj, :, :] += jj
    for ii in range(rlon):
        ilon[:, ii, :] += ii

    # Re-create a DataFrame:
    df_eur = DataFrame.from_dict(dict(ilat=ilat.reshape(-1), ilon=ilon.reshape(-1), value=values, itime=itime, itrac=itrac))
    df_eur.loc[:, 'region'] = 'eur300x200'

    # Adjust the indices to those of a glb1x1 grid:
    df_eur.loc[:, 'ilat'] += grid1.south + 90
    df_eur.loc[:, 'ilon'] += grid1.west + 180

    # ------------------
    # Reproject the glb6x4 grid on glo1x1
    fpreg = footprints[footprints.region == 'glb600x400']
    grid0 = TM5Grids.from_corners(west=-180, east=180, south=-90, north=90, dlon=6, dlat=4)
    grid1 = TM5Grids.from_corners(west=-180, east=180, south=-90, north=90, dlon=1, dlat=1)
    grid1x1 = grid1

    rlon, rlat = 6, 4
    ilat = tile(fpreg.ilat.values * rlat, (rlat, rlon, 1))
    ilon = tile(fpreg.ilon.values * rlon, (rlat, rlon, 1))
    values = tile(fpreg.value.values, (rlat, rlon, 1)).reshape(-1)
    itime = tile(fpreg.itime.values, (rlat, rlon, 1)).reshape(-1)
    itrac = tile(fpreg.itrac.values, (rlat, rlon, 1)).reshape(-1)

    for jj in range(rlat):
        ilat[jj, :, :] += jj
    for ii in range(rlon):
        ilon[:, ii, :] += ii

    df_glb = DataFrame.from_dict(dict(ilat=ilat.reshape(-1), ilon=ilon.reshape(-1), value=values, itime=itime, itrac=itrac))
    df_glb.loc[:, 'region'] = 'eur600x400'

    # ---------------------
    # Finally reproject gns1x1 on glo1x1
    df_gns = footprints[footprints.region == 'gns100x100']
    gns_west, gns_east = conf.regions['gns100x100'].lons[:2]
    gns_south, gns_north = conf.regions['gns100x100'].lats[:2]
    
    grid0 = TM5Grids.from_corners(west=gns_west+3, east=gns_east-3, south=gns_south+2, north=gns_north-2, dlon=1, dlat=1)
    df_gns.loc[:, 'ilat'] += grid0.south + 90
    df_gns.loc[:, 'ilon'] += grid0.west + 180

    # ----------------------
    # Concatenate all 3 dataframes

    df_tot = concat([df_eur, df_glb, df_gns])

    # Store all footprints in a single array
    # - array is global with dimensions time/lat/lon/obs
    #
    fp = zeros((nday, 180, 360, nobs))
    fp[df_tot.itime, df_tot.ilat, df_tot.ilon, df_tot.itrac] = df_tot.value
    #-- MVO-TODO::still hard-coding the units below!!
    da = xr.DataArray(
        fp,
        dims=('iday','lat','lon','iobs'),
        coords = {
            'iday': np.arange(nday),
            'lat': grid1x1.latc,
            'lon': grid1x1.lonc,
            'iobs': np.arange(nobs)
            },
        attrs = {
            'units' : "ppb/kgCH4/cell/s"
            }
        )
    
    return SimpleNamespace(data_table=df_tot, data=da, obsids=tracer, days=trange)


def load_adjoint_fwd(outpath : str | Path, host : str = 'cosmos', trange : date_range = None) -> DataFrame:
    """Function that codes the first cell of Guillaume's initial jupyter notebook.

    Returns pandas dataframe, where each row contains the contribution of one (emission)
    date and region to one specific obs.
    """
    yamlfile = Path(outpath) / 'tm5.yaml'
    if not yamlfile.exists():
        msg = f"yaml configuration file ***{str(yamlfile)}*** not found on system."
        raise FileNotFoundError(msg)
    conf = OmegaConf.load(yamlfile)
    conf.host = conf[host]

    # Load the observations tabled
    obs_table = read_obs_table(conf.observations.file).set_index('obsid')
    tracers = set(obs_table.tracer)
    # print(f"-->{obs_table.index}<--")
    # sta = 'cbw_207'
    # ii = np.where(obs_table.index==sta)
    # ista = ii[0][0]
    # print(f"{sta} detected at position {ista}")
    # Accumulators:
    date, region, obs, dmix = [], [], [], []

    if trange is None:
        trange = date_range(conf.run.start, conf.run.end, freq='1d')

    dmix_sta = []
    for day in trange:
        for reg in conf.run.regions:
            adjfile = day.strftime(f'{conf.run.paths.output}/adjemis/adjemis.{reg}.%Y%m%d.nc')

            # Adjoint files are written only if needed, so it may not exist for a given day/region
            if not Path(adjfile).exists():
                continue

            # I don't know which key should code for that exact path ... for now I guessed ...
            adj = xr.open_dataset(day.strftime(f'{conf.run.paths.output}/adjemis/adjemis.{reg}.%Y%m%d.nc'))

            ilons = adj.ilon.values
            ilats = adj.ilat.values
            sensi = adj['values'].values
            itrac = adj.itrac.values

            # Read the emissions. For now, I'm hardcoding this to CH4 ...
            em = xr.open_dataset(day.strftime(f'{conf.emissions.CH4.prefix}.CH4.{reg}.%Y%m%d.nc'))
            emtot = em.to_array().sum('variable').values

            for itr in set(itrac):
                date.append(day)
                region.append(reg)
                obs.append(adj.tracer.values[itr].strip().decode())

                subset = itrac == itr
                sensi_trac = sensi[subset]
                _dmix = (emtot[ilats[subset], ilons[subset]] * sensi[subset]).sum()
                # if itr==ista:
                #     msg = f"@{sta}, {day.strftime('%Y-%m-%d')}, {reg}: dmix = {_dmix}, sensi_trac min/mean/max = " \
                #     f"{sensi_trac.min()}/{sensi_trac.mean()}/{sensi_trac.max()}"
                #     # print(msg)
                #     dmix_sta.append(_dmix)
                dmix.append(_dmix)
    # print(f"@{sta}, {runend}: sum(dmix_sta)={sum(dmix_sta)}")
    # Store everything in a common dataframe. Each row contains the contribution of one date and region to one specific obs
    fwd = DataFrame.from_dict({'obs': obs, 'region': region, 'date': date, 'mix': dmix})
    return fwd
